import java.util.ArrayList;
import java.util.HashMap;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Club {
    // the primary key (ID) is auto generated by ObjectDB
    @Id 
    @GeneratedValue 
    private Integer id;
    private String clubName;
    private String clubDescription;
    private ArrayList<User> memberUsers = null;
    private HashMap<Integer, Integer> memberPrivileges = null;
    private ArrayList<Event> events = null;
    

    // a no argument constructor is required by JPA
    public Club() {
        initializeCollections();
    }

    public void initializeCollections() {
        if (memberUsers == null) memberUsers = new ArrayList<>();
        if (memberPrivileges == null) memberPrivileges = new HashMap<>();
        if (events == null) events = new ArrayList<>();
    }

    public Club(String argClubName, String argClubDesc){
        initializeCollections();
        clubName = argClubName.trim();
        clubDescription = argClubDesc.trim();
    }

    public void addMember(User user){
        initializeCollections();
        if (memberUsers.contains(user)) return;
        memberUsers.add(user);
        setMemberPrivilege(user, Privileges.NORMAL_USER);
    }

    public void removeMember(User user){
        initializeCollections();
        memberUsers.remove(user);
        memberPrivileges.remove(user.getId());
    }

    public void setMemberPrivilege(User user, Integer privilege){
        initializeCollections();
        memberPrivileges.put(user.getId(), privilege);
    }

    public void addEvent(Event event){
        if (events.contains(event)) return;
        events.add(event);
    }

    // Getters and Setters
    public Integer getId(){
        return id;
    }

    public String getClubName(){
        return clubName;
    }

    public String getClubDescription(){
        return clubDescription;
    }

    public String toString(){
        return "Club ID: " + id + " name: " + clubName + " with " + memberUsers.size() + " members";
    }
}
