import java.util.ArrayList;
import java.util.HashMap;
import java.util.Objects;

import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import embeddings.Embeddable;

@Entity
public class Club implements Embeddable {
    // the primary key (ID) is auto generated by ObjectDB
    @Id
    @GeneratedValue
    private Integer id;
    private String clubName;
    private String clubDescription;
    @ElementCollection(fetch = FetchType.EAGER)
    private ArrayList<User> memberUsers = null;
    @ElementCollection(fetch = FetchType.EAGER)
    private HashMap<Integer, Integer> memberPrivileges = null;
    @ElementCollection(fetch = FetchType.EAGER)
    private ArrayList<Event> events = null;
    private DiscussionManager discussion;

    private String iconFilename = "static/default-club-icon.png";
    private String coverFilename = "static/default-club-cover.jpg";

    private float[] embeddings;

    // a no argument constructor is required by JPA
    public Club() {
        initializeCollections();
    }

    public void initializeCollections() {
        if (memberUsers == null)
            memberUsers = new ArrayList<>();
        if (memberPrivileges == null)
            memberPrivileges = new HashMap<>();
        if (events == null)
            events = new ArrayList<>();
    }

    public Club(String argClubName, String argClubDesc) {
        initializeCollections();
        clubName = argClubName.trim();
        clubDescription = argClubDesc.trim();
        discussion = new DiscussionManager();
    }

    public DiscussionManager getDiscussion(){
        return discussion;
    }

    public ArrayList<User> getMembers() {
        return memberUsers;
    }

    public void addMember(User user) {
        initializeCollections();
        if (memberUsers.contains(user))
            return;
        memberUsers.add(user);
        setMemberPrivilege(user, Privileges.NORMAL_USER);
    }

    public void removeMember(User user) {
        initializeCollections();
        memberUsers.remove(user);
        memberPrivileges.remove(user.getId());
    }

    public void setMemberPrivilege(User user, Integer privilege) {
        initializeCollections();
        memberPrivileges.put(user.getId(), privilege);
    }

    public void addEvent(Event event) {
        if (events.contains(event))
            return;
        events.add(event);
    }

    public ArrayList<Event> getEvents() {
        return events;
    }

    // Getters and Setters
    public Integer getId() {
        return id;
    }

    public String getClubName() {
        return clubName;
    }

    public String getClubDescription() {
        return clubDescription;
    }

    public String getIconFilename() {
        return iconFilename;
    }

    public void setIconFilename(String iconFilename) {
        this.iconFilename = iconFilename;
    }

    public String getCoverFilename() {
        return coverFilename;
    }

    public void setCoverFilename(String coverFilename) {
        this.coverFilename = coverFilename;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        Club other = (Club) o;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Club ID: " + id + " name: " + clubName + " with " + memberUsers.size() + " members";
    }

    /*
     * Embeddings logic
     */

    @Override
    public String generateEmbeddingText() {
        return "Club Name: " + clubName + "\nClub Description: " + clubDescription;
    }

    @Override
    public float[] getEmbedding() {
        return embeddings;
    }

    @Override
    public void setEmbedding(float[] embeddings) {
        this.embeddings = embeddings;
    }

    @Override
    public final String getTaskType() {
        return "RETRIEVAL_DOCUMENT";
    }
}
