import java.util.ArrayList;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Club {
    // the primary key (ID) is auto generated by ObjectDB
    @Id 
    @GeneratedValue 
    private Integer id;
    private String clubName;
    private String clubDescription;
    private ArrayList<User> memberUsers;
    private ArrayList<Integer> memberPrivileges;
    

    // a no argument constructor is required by JPA
    public Club() {
    }

    public Club(String argClubName, String argClubDesc){
        clubName = argClubName.trim();
        clubDescription = argClubDesc.trim();
        memberUsers = new ArrayList<>();
        memberPrivileges = new ArrayList<>();
    }

    public void addMember(User user){
        if (memberUsers.contains(user)) return;
        memberUsers.add(user);
        memberPrivileges.add(Privileges.NORMAL_USER);
    }

    public void removeMember(User user){
        int userIndex = memberUsers.indexOf(user);
        if (userIndex == -1) return;
        memberUsers.remove(userIndex);
        memberPrivileges.remove(userIndex);
    }

    public void setMemberPrivilege(User user, Integer privilege){
        int userIndex = memberUsers.indexOf(user);
        if (userIndex == -1) return;
        memberPrivileges.set(userIndex, privilege);
    }

    // Getters and Setters
    public Integer getId(){
        return id;
    }

    public String getClubName(){
        return clubName;
    }

    public String getClubDescription(){
        return clubDescription;
    }

    public String toString(){
        return "Club ID: " + id + " name: " + clubName + " with " + memberUsers.size() + " members";
    }
}
