import java.util.ArrayList;
import java.util.HashMap;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import embeddings.Embeddable;

@Entity
public class User implements Embeddable {

    // the primary key (ID) is auto generated by ObjectDB
    @Id
    @GeneratedValue
    private Integer id = null;

    private String firstName;
    private String lastName;

    @Column(unique = true)
    private String email = "";
    private String major = "";

    private String profilePicture = "static/default-profile-picture.jpg";

    private String token = null;

    private float[] embeddings;

    @ElementCollection(fetch = FetchType.EAGER)
    private ArrayList<String> interests = null;
    @ElementCollection(fetch = FetchType.EAGER)
    private ArrayList<User> followedUsers = null;
    @ElementCollection(fetch = FetchType.EAGER)
    private HashMap<Integer, Integer> clubPrivileges = null;
    @ElementCollection(fetch = FetchType.EAGER)
    private ArrayList<Event> registeredEvents = null;
    private int privileges = Privileges.NORMAL_USER;

    private int GE250Points = 0;

    private boolean clubAndEventAlerts = true;
    private boolean generalNotifications = true;

    private boolean wantToRecieveMails = true;

    // a no argument constructor is required by JPA
    public User() {
        initializeCollections();
    }

    public User(String firstName, String lastName, String email) {
        initializeCollections();
        this.firstName = firstName.trim();
        this.lastName = lastName.trim();
        this.email = email.trim();
    }

    private void initializeCollections() {
        if (followedUsers == null)
            followedUsers = new ArrayList<>();
        if (clubPrivileges == null)
            clubPrivileges = new HashMap<>();
        if (registeredEvents == null)
            registeredEvents = new ArrayList<>();
        if (interests == null)
            interests = new ArrayList<>();
    }

    // Getters and Setters

    public boolean wantToRecieveMails() {
        return wantToRecieveMails;
    }

    public boolean wantToRecieveClubAndEventAlerts() {
        return clubAndEventAlerts;
    }

    public boolean wantToRecieveGeneralNotifications() {
        return generalNotifications;
    }

    public void setWantToRecieveMails(boolean wantToRecieveMails) {
        this.wantToRecieveMails = wantToRecieveMails;
    }

    public void setWantToRecieveClubAndEventAlerts(boolean wantToRecieveClubAndEventAlerts) {
        this.clubAndEventAlerts = wantToRecieveClubAndEventAlerts;
    }

    public void setWantToRecieveGeneralNotifications(boolean wantToRecieveGeneralNotifications) {
        this.generalNotifications = wantToRecieveGeneralNotifications;
    }

    public Integer getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getFullName() {
        return firstName + " " + lastName;
    }

    public String getEmail() {
        return email;
    }

    public String getMajor() {
        return major;
    }

    public int getGE250Points() {
        return GE250Points;
    }

    public String getProfilePicture() {
        return profilePicture;
    }

    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName.trim();
    }

    public void setLastName(String lastName) {
        this.lastName = lastName.trim();
    }

    public void setMajor(String major) {
        this.major = major.trim();
    }

    public void setGE250Points(int GE250Points) {
        this.GE250Points = GE250Points;
    }

    public void awardGE250Points(int increment) {
        if (increment <= 0)
            return;
        this.GE250Points += increment;
    }

    public void deductGE250Points(int decrement) {
        if (decrement <= 0)
            return;
        this.GE250Points -= decrement;
    }

    public void setEmail(String email) {
        if (!this.email.equals(""))
            return;
        // for now we can't support changing the email address because it introduces
        // additional complexity
        this.email = email.trim();
    }

    public void followUser(User user) {
        initializeCollections();
        followedUsers.add(user);
    }

    public void unfollowUser(User user) {
        initializeCollections();
        followedUsers.remove(user);
    }

    public void joinClub(Club club) {
        initializeCollections();
        if (isRegisteredInClub(club))
            return;
        if (hasGeneralPrivilege(Privileges.ADMIN)) {
            clubPrivileges.put(club.getId(), Privileges.ADMIN);
        } else {
            clubPrivileges.put(club.getId(), Privileges.NORMAL_USER);
        }
    }

    public boolean isRegisteredInClub(Club club) {
        initializeCollections();
        Integer clubId = club.getId();
        return clubPrivileges.containsKey(clubId);
    }

    public void setClubPrivilege(Club club, int privilege) {
        initializeCollections();
        // note that the privilege flag here is a composite flag created by using
        // bitwise OR
        // unless the user is getting banned, then the flag is just 0
        clubPrivileges.put(club.getId(), privilege);
    }

    public void leaveClub(Club club) {
        initializeCollections();
        if (!isRegisteredInClub(club))
            return;
        clubPrivileges.remove(club.getId());
    }

    public boolean isAdmin() {
        return (privileges & Privileges.ADMIN) != 0;
    }

    public boolean hasClubPrivilege(Club club, int privilegeType) {
        initializeCollections();
        if (!isRegisteredInClub(club))
            return false;
        // note that the privilegeType flag here is NOT a composite flag
        int currentPrivilege = clubPrivileges.get(club.getId());
        if (currentPrivilege <= Privileges.NORMAL_USER)
            return false;
        return ((currentPrivilege & privilegeType) != 0);
    }

    public boolean hasGeneralPrivilege(int privilegeType) {
        if (privileges <= Privileges.NORMAL_USER)
            return false;
        return ((privileges & privilegeType) != 0);
    }

    public void addInterest(String interest) {
        initializeCollections();
        interests.add(interest);
    }

    public void removeInterest(String interest) {
        initializeCollections();
        interests.remove(interest);
    }

    public void setInterests(ArrayList<String> interests) {
        initializeCollections();
        this.interests = interests;
    }

    public ArrayList<String> getInterests() {
        initializeCollections();
        return new ArrayList<>(interests);
    }

    public ArrayList<Integer> getClubIds() {
        initializeCollections();
        return new ArrayList<>(clubPrivileges.keySet());
    }

    public int getPrivilege() {
        initializeCollections();
        return privileges;
    }

    public HashMap<Integer, Integer> getClubPrivileges() {
        initializeCollections();
        return clubPrivileges;
    }

    public void banUser() {
        initializeCollections();
        for (int i = 0; i < embeddings.length; i++) {
            embeddings[i] = 0;
        }
        followedUsers.clear();
        token = null;
        privileges = Privileges.BANNED_USER;
    }

    public boolean isBanned() {
        return (privileges == Privileges.BANNED_USER);
    }

    public void banFromClub(Club club) {
        setClubPrivilege(club, Privileges.BANNED_USER);
    }

    public boolean isBannedFromClub(Club club) {
        initializeCollections();
        if (!clubPrivileges.containsKey(club.getId()))
            return false;
        return clubPrivileges.get(club.getId()) == Privileges.BANNED_USER;
    }

    public boolean isRegisteredToEvent(Event event) {
        return registeredEvents.contains(event);
    }

    public boolean canRegisterToEvent(Event event) {
        if (!event.isOpen())
            return false;
        for (Event registeredEvent : registeredEvents)
            if (event.conflictsWith(registeredEvent))
                return false;
        return true;
    }

    public void registerToEvent(Event event) {
        if (isRegisteredToEvent(event) || !canRegisterToEvent(event))
            return;
        registeredEvents.add(event);
    }

    public void leaveEvent(Event event) {
        registeredEvents.remove(event);
    }

    public String getToken() {
        return token;
    }

    public void generateToken() {
        token = SecureTokenGenerator.generate();
    }

    public void clearToken() {
        token = null;
    }

    public boolean validateToken(String providedToken) {
        if (token == null || providedToken == null)
            return false;
        Long storedTTL = Long.parseLong(token.substring(1 + token.lastIndexOf(':')));
        if (System.currentTimeMillis() > storedTTL)
            return false;
        // Doing some seemingly stupid things to avoid compiler optimizations that
        // might introduce timing vulnerabilities
        int counter = 0;
        for (int i = 0; i < 32; i++)
            counter += (token.charAt(i) == providedToken.charAt(i)) ? 2 : 1;
        return counter == 64;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        User other = (User) o;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "User {id=" + id + ", name='" + getFullName() + "', email='" + email + "'}";
    }

    /*
     * Embeddings logic
     */

    @Override
    public String generateEmbeddingText() {
        StringBuilder query = new StringBuilder();

        String targetObject = "student clubs and events";
        query.append("Find ")
                .append(targetObject) // construct a suitable prompt based on return type ??
                .append(" ");

        String interestsString = String.join(", ", this.interests);

        query.append(String.format("suitable for a %s student who is interested in %s.",
                this.major, interestsString));

        return query.toString();
    }

    @Override
    public float[] getEmbedding() {
        return embeddings;
    }

    @Override
    public void setEmbedding(float[] embeddings) {
        this.embeddings = embeddings;
    }

    @Override
    public final String getTaskType() {
        return "RETRIEVAL_QUERY";
    }
}
