import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class User {

    // the primary key (ID) is auto generated by ObjectDB
    @Id 
    @GeneratedValue 
    private Integer id = null;
    
    private String firstName;
    private String lastName;

    @Column(unique=true)
    private String email = "";

    private String token = null;

    private float[] embeddings;

    private List<String> interests;
    private Set<Integer> followedUsers;
    private Set<Integer> followedClubs;
    private Map<Integer, Integer> administeredClubs;
    private int privileges = Privileges.NORMAL_USER;

    // a no argument constructor is required by JPA
    public User() {
    }

    public User(String firstName, String lastName, String email) {
        this.firstName = firstName.trim();
        this.lastName = lastName.trim();
        this.email = email.trim();
    }

    // Getters and Setters
    public Integer getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getFullName() {
        return firstName + " " + lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName.trim();
    }

    public void setLastName(String lastName) {
        this.lastName = lastName.trim();
    }

    public void setEmail(String email) {
        if (!this.email.equals("")) return;
        // for now we can't support changing the email address because it introduces additional complexity
        this.email = email.trim();
    }

    public void followUser(Integer id) {
        followedUsers.add(id);
    }

    public void unfollowUser(Integer id) {
        followedUsers.remove(id);
    }

    public void followClub(Integer id) {
        followedClubs.add(id);
    }

    public void unfollowClub(Integer id) {
        followedClubs.remove(id);
    }

    public void setClubPrivilege(Integer id, int privilege) {
        // note that the privilege flag here is a composite flag created by using bitwise OR
        administeredClubs.put(id, privilege);
    }

    public void removeClubPrivilege(Integer id) {
        administeredClubs.remove(id);
    }

    public boolean isAdmin() {
        return (privileges & Privileges.ADMIN) != 0;
    }

    public boolean hasClubPrivilege(Integer id, int privilegeType) {
        // note that the privilegeType flag here is NOT a composite flag
        int currentPrivilege = administeredClubs.get(id);
        if (currentPrivilege <= Privileges.NORMAL_USER) return false;
        return ((currentPrivilege & privilegeType) != 0);
    }

    public void addInterest(String interest) {
        interests.add(interest);
    }

    public void removeInterest(String interest) {
        interests.remove(interest);
    }

    public void setInterests(List<String> interests) {
        this.interests = interests;
    }

    public void banUser() {
        for (int i = 0; i < embeddings.length; i++) {
            embeddings[i] = 0;
        }
        followedClubs.clear();
        followedUsers.clear();
        administeredClubs.clear();
        token = null;
        privileges = Privileges.BANNED_USER;
    }

    public boolean isBanned() {
        return (privileges == Privileges.BANNED_USER);
    }

    public void banFromClub(Integer id) {
        followedClubs.remove(id);
        administeredClubs.put(id, Privileges.BANNED_USER);
    }

    public String getToken() {
        return token;
    }

    public void generateToken() {
        token = SecureTokenGenerator.generate();
    }

    public boolean validateToken(String providedToken) {
        // FIXME: there is a timing vulnerability to fix here, we should use constant time comparison
        if (token == null ||providedToken == null) return false;
        Long storedTTL = Long.parseLong(token.substring(1 + token.lastIndexOf(':')));
        if (System.currentTimeMillis() > storedTTL) return false;
        return providedToken.equals(token);
    }

    @Override
    public String toString() {
        return "User {id=" + id + ", name='" + getFullName() + "', email='" + email + "'}";
    }
}